THEME_CATALOG = [
    {
        "slug": "hiking",
        "name": "徒步登山",
        "icon": "Mountain",
        "image_url": "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=80",
        "description": "山脊步道、峡谷栈道与森林穿越，适合想把旅行节奏交给双脚的人。",
        "guide": "优先选择成熟步道，查看天气、海拔和返程交通；雨后山路注意防滑。",
        "keywords": ["徒步", "登山", "步道", "山岳", "峡谷", "森林"],
        "season": "春秋最佳",
        "audience": "体力较好、喜欢户外的人",
        "route_idea": "游客中心 - 核心步道 - 观景台 - 下山接驳",
        "sort_order": 10,
    },
    {
        "slug": "heritage",
        "name": "人文古迹",
        "icon": "Landmark",
        "image_url": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",
        "description": "古城、寺庙、遗址、博物馆与名人故居，把目的地的时间线串起来。",
        "guide": "提前看展陈和讲解时间，工作日上午更适合慢游和拍摄细节。",
        "keywords": ["古迹", "历史", "文化", "博物馆", "寺庙", "遗址", "故居", "陵"],
        "season": "四季皆宜",
        "audience": "历史文化爱好者",
        "route_idea": "历史街区 - 博物馆 - 古建群 - 夜间街巷",
        "sort_order": 20,
    },
    {
        "slug": "photo",
        "name": "摄影打卡",
        "icon": "Camera",
        "image_url": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
        "description": "日出日落、观景平台、城市地标与季节限定景观，帮你快速锁定机位。",
        "guide": "日出前 1 小时到达机位，带长焦和轻便三脚架，避开正午硬光。",
        "keywords": ["摄影", "打卡", "观景", "日出", "日落", "广场", "风景"],
        "season": "春秋光线稳定",
        "audience": "摄影玩家、内容创作者",
        "route_idea": "晨光机位 - 午后街区 - 日落观景台",
        "sort_order": 30,
    },
    {
        "slug": "nature",
        "name": "自然风光",
        "icon": "TreePine",
        "image_url": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
        "description": "山水、湖泊、森林、瀑布和湿地，适合需要放空和低噪旅行的人。",
        "guide": "雨后初晴、清晨和傍晚更容易看到云雾、水汽和柔和光线。",
        "keywords": ["自然风光", "山水", "森林", "峡谷", "瀑布", "湖", "山", "湿地", "公园"],
        "season": "春夏秋皆宜",
        "audience": "自然爱好者、轻度户外人群",
        "route_idea": "湖畔步行 - 森林栈道 - 观景平台",
        "sort_order": 40,
    },
    {
        "slug": "food",
        "name": "美食之旅",
        "icon": "Utensils",
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
        "description": "老街、小吃、夜市和城市味道，把景区周边的吃喝体验纳入行程。",
        "guide": "优先找本地老店和市场，景区核心区用餐高峰建议错开 30-60 分钟。",
        "keywords": ["美食", "小吃", "特色菜", "老街", "街区", "夜市", "文化"],
        "season": "四季皆宜",
        "audience": "城市漫游、美食爱好者",
        "route_idea": "景区游览 - 老街小吃 - 夜市散步",
        "sort_order": 50,
    },
    {
        "slug": "drive",
        "name": "自驾旅行",
        "icon": "Car",
        "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80",
        "description": "山地公路、湖岸环线、跨城串联和周末短途，强调停车和补给可控。",
        "guide": "提前确认停车场、充电桩和返程拥堵；山区留足弯道和落石风险缓冲。",
        "keywords": ["自驾", "公路", "环线", "停车", "服务区", "风景名胜", "国家级景点"],
        "season": "秋季最舒适",
        "audience": "家庭、情侣、周边游用户",
        "route_idea": "城市出发 - 沿途观景 - 核心景区 - 返程补给",
        "sort_order": 60,
    },
    {
        "slug": "family",
        "name": "亲子乐园",
        "icon": "Baby",
        "image_url": "https://images.unsplash.com/photo-1502086223501-7ea244bce1e4?auto=format&fit=crop&w=1200&q=80",
        "description": "动物园、主题乐园、亲水公园和低强度步行路线，减少排队和体力消耗。",
        "guide": "确认卫生间、母婴室、餐饮和休息区；避开正午和长距离台阶路线。",
        "keywords": ["亲子", "乐园", "动物园", "水族馆", "儿童", "游乐", "公园"],
        "season": "周末和小长假",
        "audience": "亲子家庭、低龄儿童",
        "route_idea": "上午核心项目 - 午间休息 - 下午轻体验",
        "sort_order": 70,
    },
    {
        "slug": "summer",
        "name": "避暑胜地",
        "icon": "Snowflake",
        "image_url": "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1200&q=80",
        "description": "高海拔山地、森林峡谷、湖泊和漂流，适合炎热季节的清凉旅行。",
        "guide": "山区早晚温差大，漂流和亲水项目注意换洗衣物与安全提示。",
        "keywords": ["避暑", "清凉", "漂流", "山", "森林", "峡谷", "湖", "瀑布"],
        "season": "6-9 月",
        "audience": "夏季周边游、家庭短途",
        "route_idea": "森林步道 - 峡谷亲水 - 傍晚民宿",
        "sort_order": 80,
    },
    {
        "slug": "flower",
        "name": "赏花踏青",
        "icon": "Flower2",
        "image_url": "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1200&q=80",
        "description": "花海、公园、古镇春景和轻徒步，把花期、天气和交通一起考虑。",
        "guide": "花期受天气影响明显，出发前确认最新花况；周末尽量早到。",
        "keywords": ["赏花", "花海", "踏青", "公园", "樱花", "油菜花", "湿地"],
        "season": "3-5 月",
        "audience": "轻旅行、拍照、家庭出游",
        "route_idea": "花田入口 - 主观景台 - 古镇或市集",
        "sort_order": 90,
    },
    {
        "slug": "snow",
        "name": "冰雪世界",
        "icon": "Sun",
        "image_url": "https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?auto=format&fit=crop&w=1200&q=80",
        "description": "滑雪、冰瀑、雪景、温泉和冬季城市游，重点关注交通与保暖。",
        "guide": "确认道路结冰、缆车开放和装备租赁；温泉后避免剧烈运动。",
        "keywords": ["冰雪", "滑雪", "雪", "温泉", "冰瀑", "冬季"],
        "season": "12-2 月",
        "audience": "冬季旅行、滑雪入门者",
        "route_idea": "雪场体验 - 温泉恢复 - 夜间热饮街区",
        "sort_order": 100,
    },
]

THEME_TERMS = {item["name"]: item["keywords"] for item in THEME_CATALOG}
THEME_BY_NAME = {item["name"]: item for item in THEME_CATALOG}
